### ISSUE TITLE
Tab drawing over tab width when expandedTabIndicator is activated

### ISSUE THREAD

**Issue by rmobis** [spywhere/vscode-whiteviz#10]
Whenever a tab character does not take its full defined width (because it does not start at a multiple of its width), the drawing overlaps is boundaries and draws over the next words, as can be seen in the image below.

![image](https://user-images.githubusercontent.com/2119933/52060917-65635500-2554-11e9-8f92-ed6575847b40.png)

It should be possible to figure out how many characters the tab is actually taking with some simple math (`w - (p % w)`, where `w` is the tab width and `p` is the specific character's position) and draw only the correct amount of dashes.

**PS:** I'm not sure how to solve this problem when we couple this with `expandedTabMargin`. Maybe try using narrower dash glyphs?

**Comment by spywhere** [comment]
Sorry for such a long response. Thanks for the finding anyway, this is something I didn't expected, definitely worth checking.

Also, the extension do have support for custom indicators (for whitespace, for tab and for line ending)

**Comment by gsemet** [comment]
Reproduced on Python code as well.

**Comment by kanlukasz** [comment]
Same problem in PHP:

![obraz](https://user-images.githubusercontent.com/30685349/58011212-0f5df180-7af2-11e9-8ec2-0326d04bb21d.png)

**Comment by spywhere** [comment]
Upcoming on the next release...

_Mind the tab indicator on the first line_
<img width="447" alt="Screen Shot 2562-07-24 at 23 25 26" src="https://user-images.githubusercontent.com/1087399/61810850-5f4a9300-ae6a-11e9-920b-840cc91359b3.png">

**Comment by spywhere** [comment]
Implemented in v0.7.0

**Comment by kanlukasz** [comment]
Still not working properly or I missed something?

```
Version: 1.36.1 (system setup)
Commit: 2213894ea0415ee8c85c5eea0d0ff81ecc191529
Date: 2019-07-08T22:59:35.033Z
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

![obraz](https://user-images.githubusercontent.com/30685349/61997379-1deff880-b0a1-11e9-80e0-1bfe95cec507.png)

![obraz](https://user-images.githubusercontent.com/30685349/61997395-4bd53d00-b0a1-11e9-83ae-8da884c52708.png)

**Comment by rmobis** [comment]
@kanlukasz the update on VSCode that fixes this only landed in Insiders 4 days ago, so I guess it'll take some time until it's working on the main build.
