### ISSUE TITLE
[Featured request] Add litlle space beetwen tabs line

### ISSUE THREAD

**Issue by kanlukasz** [spywhere/vscode-whiteviz#11]
Hello, thanks for this add-on.

I have one idea to improve visible tabs lines with option `"whiteviz.expandedTabIndicator": true`
Maybe could you add a little space 1 or 2px beetwen each tabs lines.
Something like this:

![obraz](https://user-images.githubusercontent.com/30685349/57450799-bf646c80-725f-11e9-860d-1797d818e4f8.png)

**Comment by spywhere** [comment]
Please check #4 seems like it's what you want here. Feel free to reopen the issue and elaborate more on what should be done. Thanks.
