### ISSUE TITLE
Toggle command / synchronize with VSCode's behavior?

### ISSUE THREAD

**Issue by borekb** [spywhere/vscode-whiteviz#12]
The behavior of this extension is awesome when I want to see whitespace but unless I missed something (and there are quite a few configuration options 😁), it's not easy to toggle it quickly.

A couple of thoughts around this:

- VSCode has the **View: Toggle Render Whitespace** command, something similar could exist for this extension.
- Even better from my point of view would be to (optionally) tie this extension to VSCode's options. From my point of view, VSCode simply misses another value in its `editor.renderWhitespace` option, like `onSelection`, and there could possibly be an option for that in WhiteViz. For example:
    - `whitewiz.active` with the following values:
        - `always` – current behavior
        - `whenVSCodeIsSetToRenderWhitespace` – just an ugly example but hopefully gets the point across

With the latter option, the built-in **Toggle Render Whitespace** command would activate/deactive WhiteViz, as well as setting the `editor.renderWhitespace` option.

**Comment by spywhere** [comment]
Would it be better to have WhiteViz asking you whether you want to continue with current settings, change to WhiteViz or ask for later, when it detects that you are setting render whitespace to `false`?

Like `Use Current` `Use WhiteViz` `Ask Me Later` dialog

**Comment by borekb** [comment]
Hmm I can see how this could quickly become confusing... Now that I think about it again, I'm not sure what my feature request is.

I thought I wanted a toggle – a command to either show or not show WhiteViz on selection. The idea was that most of the time, I don't care about whitespace so I'd just have everything turned off. Only when I'd need it, I'd turn on WhiteViz. However, now I think that if it's behind a command, I might as well turn on VSCode's built-in whitespace visualization temporarily.

So I'm not sure if this issue makes sense – probably not :) Sorry for that.
