### ISSUE TITLE
Hang VSCode when sending Ctrl+A in big files

### ISSUE THREAD

**Issue by evandrocoan** [spywhere/vscode-whiteviz#3]
I opened  a file file with about 20.000 lines, then pressed `Ctrl+A` to select all the lines, then VSCode stopped responding for several minutes, until I accepted his offer to restart the window.

**Comment by spywhere** [comment]
Thanks for the issue. That's expectable due to the way WhiteViz render the special character for whitespaces. I'll keep this issue open and keep you up to date if I have any progress on how to handle this.

**Comment by Enteleform** [comment]
### Suggestion:

Add a `maxSelectionSize: int` property that disables rendering if a selection contains more than `n` characters.

Similar to the `search_threshold: 10000` default of SublimeText's BracketHighlighter.

**Comment by spywhere** [comment]
Thanks @Enteleform. I also thinking about that, but also it would be better if it render progressively. However, I don't think VSCode API allow me to do progressive decoration update.

**Comment by spywhere** [comment]
This feature has been implemented in WhiteViz v0.4.0.
