### ISSUE TITLE
Feature Request: expandedTabPadding

### ISSUE THREAD

**Issue by Enteleform** [spywhere/vscode-whiteviz#4]
In an attempt to match SublimeText's tab highlighting style, I tried using `expandedTabIndicator: true` (*which is close but removes the abilty to see individual tab characters*) and `tabIndicator: "—"` (*which is left-aligned, so doesn't look that great*).

The `expandedTabPadding: int` setting would work in tandem with `expandedTabIndicator`, adding an `n` pixel gap on either side of each indent guide.

Here's an example of [1 & 2] the settings I initially tried and [3 & 4] the functionality I'm proposing.
![whiteviz](https://user-images.githubusercontent.com/10906415/31062074-cb0174c0-a6f5-11e7-9e09-f160690c1ce8.png)

**Comment by spywhere** [comment]
Adding a padding to either left or right is surely possible, but dynamic tab indicator, however, is not. Would it be okay to you if you set `tabIndicator` to be `-` (dash) and use padding to mimic the look of the 4th one (and may be smaller indicator for the 3rd)?

**Comment by Enteleform** [comment]
Gotcha, just checked the source code out & noticed that the full-width line is a repeated em-dash, thought it might have been a generated line or something.&nbsp; Just started migrating my SublimeText workflow over today & haven't had a chance to check out the API yet.&nbsp; Is it possible to use generated graphics in-line with code?

An offset like you described would be cool if the indent-guide based offsets aren't possible, pretty much just trying to get some centered almost-full-width tab indicators.

**Comment by spywhere** [comment]
Nope, VSCode doesn't have any graphic related API available for extensions. That's also why Guides (another extension of mine) has trouble with rendering guidelines on empty spaces.

**Comment by Enteleform** [comment]
> Guides (another extension of mine)

Dope 👍 
That was one of the things I was gonna hit once I start exploring extensions.

Got my guides set up perfectly now : )
![guides](https://user-images.githubusercontent.com/10906415/31064358-7efa7360-a709-11e7-975c-19517f427a2f.PNG)
Now just gotta figure out how to make a theme...

**Comment by spywhere** [comment]
This feature has been implemented in v0.4.1.

**Comment by spywhere** [comment]
Implementation details...

When you set `expandedTabMargin` to `1` while your editor tab size is `4`, WhiteViz will create a 3-character tab indicator with half a character offset from both side. This will create an illusion of centered indicator as the issue intended to be. Hence, maximum margin allowed to be set should be less than current editor tab size, otherwise, there will be no tab indicator at all.

**Comment by Enteleform** [comment]
Awesome, looks great 👍 
Thanks!
