### ISSUE TITLE
Not showing whitespace when selecting over 501 lines.

### ISSUE THREAD

**Issue by samal-rasmussen** [spywhere/vscode-whiteviz#5]
I see whitespace visualization when I select less than or equal to 501 lines, but as soon as I go over that the it disappears.

First I though that it was broken on select all (ctrl+a), but then I noticed that it worked in some files and not in others. Figured out that the difference was file size.

I am not sure if this started on update to 1.18, but I just noticed it today and I did the upgrade yesterday.

I tried reintalling WhiteViz and restarting vscode to no avail.

**Comment by spywhere** [comment]
That's expectable. To make the extension much more responsive, there's a limit that will be used when you select more than specific threshold (the default value is 500). You can tweak the settings via `whiteviz.maximumLimit`. Feel free to open the issue again if this is not the case.

**Comment by samal-rasmussen** [comment]
Ah I see that's documented under Contributions-Settings when you open the WhiteViz extension page in vscode. Thanks :)

Not important at all buuut I can definitely select line 1 up to line 501 and get whitespace visualization though. Shouldn't I expect it to only work from 1 to 500 when the limit is 500? (feel free to ignore)

**Comment by spywhere** [comment]
It should visualize the whitespace up to 500 lines (assume the limit is 500). However, the way 500 is count would be like this (given that `<` is a beginning of the selection and `>` is the end).

This should highlight the whitespace...
```
Line 1  : <abcdef
Line 2  :  abcdef
Line ...:  abcdef
Line 499:  abcdef
Line 500:  abcdef>
Line 501:  abcdef
```

While this shouldn't...
```
Line 1  : <abcdef
Line 2  :  abcdef
Line ...:  abcdef
Line 499:  abcdef
Line 500:  abcdef
Line 501: >abcdef
```

**Comment by samal-rasmussen** [comment]
The second of those two examples is giving me whitespace visualization.

**Comment by spywhere** [comment]
Huh, that's new. I'll fix it then. Nice catch on this by the way, thanks.
