### ISSUE TITLE
Not render single spaces between words

### ISSUE THREAD

**Issue by modkaffes** [spywhere/vscode-whiteviz#6]
Great plugin! Should be part of the core.

Can you consider implementing functionality like in `"editor.renderWhitespace": "boundary"`?
IMHO, rendering the single spaces between words is a bit noisy, as the purpose of this plugin (the way I see) it is to quickly see random trailing spaces and differences in indentation.

**Comment by spywhere** [comment]
At this moment, WhiteViz supports to render the indentations however, the trailing space still missing out. I will keep you update once I working on it.

**Comment by modkaffes** [comment]
Actually, it supports trailing whitespace:
![image](https://user-images.githubusercontent.com/1829897/34951767-fe1d1b34-fa1f-11e7-8624-71d7a2c19a40.png)

What I really requested was an option to not render *single* spaces between words or symbols; something like this:
![image](https://user-images.githubusercontent.com/1829897/34951831-399eb122-fa20-11e7-8515-bbf6b1aa8cfc.png)

**Comment by spywhere** [comment]
I mean, there is an option (`whiteviz.visualizeOnlyIndentation`) to visualize only the indentation, but there is none for trailing spaces.

**Comment by modkaffes** [comment]
Ah, now I get it. 

What about the single spaces? Is it hard to implement?

**Comment by spywhere** [comment]
Not that hard. Definitely possible.

**Comment by modkaffes** [comment]
🙏

**Comment by spywhere** [comment]
This feature has been implemented in v0.4.3.

**Comment by modkaffes** [comment]
@spywhere nice! Thank you
