### ISSUE TITLE
Indicators are not updated upon changing indentation of selections with newline

### ISSUE THREAD

**Issue by hippotastic** [spywhere/vscode-whiteviz#7]
## Reproduction steps
1. Set VS code settings "editor.insertSpaces" and "editor.detectIndentation" to false.
2. Create a new text file and insert three lines like this:
    ```
    A
    B
    C
    ```
3. Select the first two lines and ensure the cursor is on the beginning of the third line (in other words, the selection must include a trailing newline character).
4. Press tab to increase indentation of the selected lines a few times.

## Expected outcome
Tab characters are displayed inside the selection for each additional level of indentation.

## Actual outcome
The additional indentation levels do not cause new tab characters to be displayed. After changing the selection, the tab characters appear correctly.

**Comment by spywhere** [comment]
Nice catch, thanks. I'll let you know once the fix is up.

**Comment by spywhere** [comment]
This issue has been fixed in v0.4.4
