### ISSUE TITLE
[Feature Request] Include line endings

### ISSUE THREAD

**Issue by Zooce** [spywhere/vscode-whiteviz#8]
This is a simple request to render line endings as well. There are a couple of projects that show them already, but they're displayed all the time... (https://github.com/jhartell/vscode-line-endings and https://github.com/sohamkamani/code-eol for example).

**Comment by spywhere** [comment]
Shouldn't be too hard, will let you know on any progress.

**Comment by spywhere** [comment]
Implemented in v0.6.0.
